export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const SIGNIN_START = 'SIGNIN_START';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAIL = 'SIGNIN_FAIL';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const ADD_CHALLENGE_START = 'ADD_CHALLENGE_START';
export const ADD_CHALLENGE_SUCCESS = 'ADD_CHALLENGE_SUCCESS';
export const ADD_CHALLENGE_FAIL = 'ADD_CHALLENGE_FAIL';
export const ADD_CHALLENGE_INIT = 'ADD_CHALLENGE_INIT';

